version: '3.8'

services:
    pgvector:
        # postgres with the pgvector extension
        image: pgvector/pgvector:pg16
        container_name: baxus-bob-db
        environment:
            - POSTGRES_USER=baxus
            - POSTGRES_PASSWORD=baxuspwd
            - POSTGRES_DB=baxus
        ports:
            - "5452:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U baxus -d baxus"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - pgvector_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: baxus-bob-db-ui
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - pgvector
        volumes:
            - ./pgadmin-config/servers.json:/pgadmin4/servers.json

volumes:
    pgvector_data:
